name: .NET Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build GTAVCSMM
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
          submodules: recursive

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.x

    - name: Restore project dependencies
      run: dotnet restore

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build 64bit release
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 GTAVCSMM.sln /warnaserror

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
       retention-days: 0
       name: binary
       path: |
            bin/x64/Release/GTAVCSMM.exe

  check_detections:
    runs-on: ubuntu-latest
    name: Check for detections in Binary and notify if necesarry
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: binary

      - name: Test file for detected bits
        uses: Yimura/gtav-sigscan-action@v0.0.3
        with:
          file: ./GTAVCSMM.exe
      
      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: binary
